### Note 15/11/23 Oscar briefly looked through this script and got it to function,
### but mainly left it unchanged from Liv's version from several year's ago.

### summerGroRates.R, v0 | 16/01/20 ###
# Modified from cloneGroRates_v1.R from H&N's summer projects
# This version for Olivia's mutant characterisation via growth rates.
# Outputs .RData file for plotting, and growth params as a text
#   file for feeding to growth simulation project.

# NOTES:
# There are 3 scripts:

#   OD_functions.R                             contains all the important functions that are necessary
#   OD_data_wrangling.R        Main code (this file). Modify strain names etc. yourself
#   OD_plots.R                         Takes data objects generated by Liv_deal_w_groRate_data edited.R and plots them.

source("./R/functions.R")

### Create tidy data frames using raw & spec files

mainDirectory <- getwd()
setwd("./data")
allData <- data.frame() # create the allData frame before populating
fileNames <- c("PLT1_rep1_on8thsept.xlsx", "PLT1_rep2_on8thsept.xlsx", "PLT1_rep3_on9thsept.xlsx", "PLT1_rep4_on9thsept.xlsx", "PLT2_rep1_on10thsept.xlsx", "PLT2_rep2_on10thsept.xlsx", "PLT2_rep3_on11thsept.xlsx", "PLT2_rep4_on11thsept.xlsx")
for(fileName in fileNames) { # populate allData
  trafoData <- transformODfile(fileName = fileName, timePoints = 289)
  allData <- rbind(allData, trafoData)
}
setwd(mainDirectory)

# further cleaning and re-arranging of data:
#allData <- fixData(allData)

allData$drugs <- paste0("S", allData$STP, "-R", allData$RIF) # add column for drug environment
allData$time_hrs <- allData$time / 60 # add column for time in hours
allData$OD <- as.numeric(allData$OD) # make OD numeric
allData$blankedOD <- getBlankedODs(allData) # add column with blanked ODs

#neworder <- c(1:10) # refactor
#allData <- arrange(mutate(allData, strain = factor(strain, levels = neworder)), strain)

summarizedData <- summarize(group_by(allData, strain, drugs, rep),
                               maxGrowthRate = getGrowthParameters(time, blankedOD, h = 20, tmax = 300)["mumax"],
                               lagPhase = getGrowthParameters(time, blankedOD)["lag"],
                               rsquared = getGrowthParameters(time, blankedOD)["r2"],
                               maxOD = getGrowthParameters(time, blankedOD)["max"])
# returns NAs for all growth parameters, not sure why


######################################################################################################################
# Plotting individual growth curves:
######################################################################################################################


# plot STP mutants:

# aesthetics



strains <- c(paste0("OH_AB3STP1","IH_S07", "AB14", "HN_STP24", "HN_STP11", "OH_AB13STP3"))
dataSubset <- allData[(allData$strain %in% strains),]
dataSubset$strain <- factor(dataSubset$strain, levels = strains, labels = strains, ordered = TRUE)
plot_STP_OD <- ggplot(data=dataSubset, aes(x=time_hrs, y=OD, col=rep)) +
  geom_line(size = 0.4) +
  facet_wrap(~strain, ncol=4) +
  scale_x_continuous(name = "Time (hours)", limits = c(0, 25)) +
  scale_y_continuous(name = "Optical Density", limits = c(0, 1.2))

dataSubset[dataSubset$time == 20,]
nrow(dataSubset[dataSubset$time == 20,])

# save as pdf:
ggsave("final_plot_STP_OD.pdf", plot = plot_STP_OD, height=300, width=400, 
       units="mm", dpi = 300, limitsize = TRUE, path = "./plots")


# plot RIF mutants:

# aesthethiccccccs



dataSubset[dataSubset$time == 20,]
nrow(dataSubset[dataSubset$time == 20,])

strains <- c(paste0("IH_R24", "IH_R22", "IH_R27", "OH_RIF4", "OH_RIF2", "OH_AB13RIF1", "HN_RIF3", "HN_RIF18", "HN_RIF7", "HN_RIF2"))
dataSubset <- allData[(allData$strain %in% strains),]
dataSubset$strain <- factor(dataSubset$strain, levels = strains, labels = strains, ordered = TRUE)
plot_RIF_OD <- ggplot(data=dataSubset, aes(x=time_hrs, y=OD, col=rep)) +
  geom_line(size = 0.4) +
  facet_wrap(~strain, ncol=4) +
  scale_x_continuous(name = "Time (hours)", limits = c(0, 25)) +
  scale_y_continuous(name = "Optical Density", limits = c(0, 1.2))

# save as pdf:
ggsave("./plots/final_plot_RIF_OD.pdf", plot = plot_RIF_OD, height=300, width=400, 
       units="mm", dpi = 300, limitsize = TRUE, path = "./plots")

#copied to plot wild-dtypes as the mutants were plotted
# plot Wild-type strains mutants:

strains <- c(paste0("AB13", "AB3")
dataSubset <- allData[(allData$strain %in% strains),]
dataSubset$strain <- factor(dataSubset$strain, levels = strains, labels = strains, ordered = TRUE)
plot_STP_OD <- ggplot(data=dataSubset, aes(x=time_hrs, y=OD, col=rep)) +
  geom_line(size = 0.4) +
  facet_wrap(~strain, ncol=4) +
  scale_x_continuous(name = "Time (hours)", limits = c(0, 25)) +
  scale_y_continuous(name = "Optical Density", limits = c(0, 1.2))

dataSubset[dataSubset$time == 20,]
nrow(dataSubset[dataSubset$time == 20,])

# save as pdf:
ggsave("./plots/final_plot_WT_OD.pdf", plot = plot_WT_OD, height=300, width=400, 
       units="mm", dpi = 300, limitsize = TRUE, path = "./plots")










# end. #